name: SonarQube analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4 
      - name: Analyze with SonarQube
        uses: SonarSource/sonarqube-scan-action@7295e71c9583053f5bf40e9d4068a0c974603ec8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          args:
            -Dsonar.projectKey= jaiyesh024_v4_Adikrish
      - name: python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install dependancies
        run: |
          pip install -r requirements.txt
          pip install flake8 pytest
      - name: linting
        run: flake8 .
      - name: run test
        run: pytest
